language: php

sudo: false

php:
  - 5.6
  - 7.0

before_script:
  - sudo apt-get update
  - sudo apt-get install phploc pdepend
  - composer selfupdate --quiet
  - composer install --prefer-dist --no-interaction --no-progress

script:
  ant
